apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mqtt-jks-secret
  namespace: {{ .Release.Namespace }}
stringData:
  client.jks.password: {{ .Values.KEYSTORE_PASSWORD }}
data:
  client.jks: {{ .Values.KEYSTORE_DATA }}
